# Generated by Django 4.0.4 on 2022-04-28 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MiniBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postName', models.CharField(max_length=100)),
                ('publisTime', models.DateField()),
                ('description', models.CharField(max_length=250)),
                ('postText', models.CharField(max_length=1000)),
            ],
        ),
    ]
