# Generated by Django 4.0.4 on 2022-04-28 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniBlog', '0002_alter_miniblog_publistime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miniblog',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='miniblog',
            name='postText',
            field=models.TextField(),
        ),
    ]
