# Generated by Django 4.0.4 on 2022-04-30 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miniBlog', '0003_alter_miniblog_description_alter_miniblog_posttext'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='miniblog',
            name='postText',
        ),
    ]
